const feedData = [
    { category: "SCIENCE", title: "Which New York City Subway MetroCard to Buy?", desc: "Duis eleifend nunc sit amet mi dapibus ornare mauris eget mattis.." },
    { category: "ARTS, POLITICS", title: "Physiological Responses to Rock Climbing in Young Climbers", desc: "Sed nec blandit nibh mauris eget mattis.." },
    { category: "ECONOMY", title: "A Better Way to Educate Primary School Children", desc: "Vivamus laoreet non mauris eget mattis mauris eget mattis." },
    { category: "In Art", title: "A Better Way to Educate Primary School Children", desc: "Vivamus laoreet non mauris eget mattis mauris eget mattis.." },
    { category: "TECH", title: "Latest Trends in Technology", desc: "Cras vehicula lorem et ex facilisis, quis dictum ex blandit." },
    { category: "LIFESTYLE", title: "5 Ways to Improve Your Daily Routine", desc: "Proin ut ante vitae enim lacinia sollicitudin mauris eget mattis.." },
    { category: "SPORTS", title: "Local Team Clinches Victory in Finals", desc: "Vestibulum ante ipsum primis in faucibus orci luctus mauris eget mattis.." },
    { category: "ENTERTAINMENT", title: "Exclusive Interview with a Rising Star", desc: "Nam facilisis, eros nec eleifend vulputate mauris eget mattis.." },
    { category: "SCIENCE", title: "Which New York City Subway MetroCard to Buy?", desc: "Duis eleifend nunc sit amet mi dapibus ornare mauris eget mattis.." },
    { category: "ARTS, POLITICS", title: "Physiological Responses to Rock Climbing in Young Climbers", desc: "Sed nec blandit nibh mauris eget mattis.." },
    { category: "ECONOMY", title: "A Better Way to Educate Primary School Children", desc: "Vivamus laoreet non mauris eget mattis mauris eget mattis." },
    { category: "In Art", title: "A Better Way to Educate Primary School Children", desc: "Vivamus laoreet non mauris eget mattis mauris eget mattis.." },
    { category: "TECH", title: "Latest Trends in Technology", desc: "Cras vehicula lorem et ex facilisis, quis dictum ex blandit." },
    { category: "LIFESTYLE", title: "5 Ways to Improve Your Daily Routine", desc: "Proin ut ante vitae enim lacinia sollicitudin mauris eget mattis.." },
    { category: "SPORTS", title: "Local Team Clinches Victory in Finals", desc: "Vestibulum ante ipsum primis in faucibus orci luctus mauris eget mattis.." },
    { category: "ENTERTAINMENT", title: "Exclusive Interview with a Rising Star", desc: "Nam facilisis, eros nec eleifend vulputate mauris eget mattis.." },
    { category: "SCIENCE", title: "Which New York City Subway MetroCard to Buy?", desc: "Duis eleifend nunc sit amet mi dapibus ornare mauris eget mattis.." },
    { category: "ARTS, POLITICS", title: "Physiological Responses to Rock Climbing in Young Climbers", desc: "Sed nec blandit nibh mauris eget mattis.." },
    { category: "ECONOMY", title: "A Better Way to Educate Primary School Children", desc: "Vivamus laoreet non mauris eget mattis mauris eget mattis." },
    { category: "In Art", title: "A Better Way to Educate Primary School Children", desc: "Vivamus laoreet non mauris eget mattis mauris eget mattis.." },
    { category: "TECH", title: "Latest Trends in Technology", desc: "Cras vehicula lorem et ex facilisis, quis dictum ex blandit." },
    { category: "LIFESTYLE", title: "5 Ways to Improve Your Daily Routine", desc: "Proin ut ante vitae enim lacinia sollicitudin mauris eget mattis.." },
    { category: "SPORTS", title: "Local Team Clinches Victory in Finals", desc: "Vestibulum ante ipsum primis in faucibus orci luctus mauris eget mattis.." },
    { category: "ENTERTAINMENT", title: "Exclusive Interview with a Rising Star", desc: "Nam facilisis, eros nec eleifend vulputate mauris eget mattis.." },
    { category: "SCIENCE", title: "Which New York City Subway MetroCard to Buy?", desc: "Duis eleifend nunc sit amet mi dapibus ornare mauris eget mattis.." },
    { category: "ARTS, POLITICS", title: "Physiological Responses to Rock Climbing in Young Climbers", desc: "Sed nec blandit nibh mauris eget mattis.." },
    { category: "ECONOMY", title: "A Better Way to Educate Primary School Children", desc: "Vivamus laoreet non mauris eget mattis mauris eget mattis." },
    { category: "In Art", title: "A Better Way to Educate Primary School Children", desc: "Vivamus laoreet non mauris eget mattis mauris eget mattis.." },
    { category: "TECH", title: "Latest Trends in Technology", desc: "Cras vehicula lorem et ex facilisis, quis dictum ex blandit." },
    { category: "LIFESTYLE", title: "5 Ways to Improve Your Daily Routine", desc: "Proin ut ante vitae enim lacinia sollicitudin mauris eget mattis.." },
    { category: "SPORTS", title: "Local Team Clinches Victory in Finals", desc: "Vestibulum ante ipsum primis in faucibus orci luctus mauris eget mattis.." },
    { category: "ENTERTAINMENT", title: "Exclusive Interview with a Rising Star", desc: "Nam facilisis, eros nec eleifend vulputate mauris eget mattis.." },
  ];
  
  export const latestArticles = [
    "The Ultimate Guide to New York’s Favorite Food",
    "Salty Peanut-Pretzel Ice Cream Cake",
    "A Cool Solution for Hot Summer Nights",
    "Full Irish Breakfast In Manhattan",
    "When to Cook Your Vegetables Long Past “Done”",
    "Overcoming Your Fear Of The Kitchen",
    "Want to Make Creamed Corn Into a Meal? Add Shrimp",
    "Why Healthy Eating Doesn’t Mean Dieting",
    "A Quick, Satisfying Fix for Weeknight Chicken",
    "Fresh Food on TV: Weekend Edition",
    "When to Cook Your Vegetables Long Past “Done”",
  ];

  export default feedData;

